### ISSUE TITLE
Deep Learning Model Creator

### ISSUE THREAD

**Issue by 12Diego06Martinez** [12Diego06Martinez/Python-Furuta-Pendulum#22]
## 1. Descripción

Poder crear un modelo de deep learning conformado por distintas capas densas. La configuración del diseño se debe poder hacer a través de un yaml de configuración.

### 2.1. Básicos

- [ ] Modificar input shape
- [ ] Modificar output shape
- [ ] Especificar número de neuronas en cada capa
- [ ] Especificar función de activación de cada capa
- [ ] Especificar función de pérdida
- [ ] Especificar optimizador y learning rate inicial
- [ ] Especificar número de epochs
- [ ] Especificar batch size
- [ ] Definir cuál es el target
- [ ] Definir tamaños de los datasets de validación y test
 
### 2.2. Avanzados

- [ ] Usar o no scaler, tipo de scaler y rango del scaler
- [ ] Especificar callbacks como early stopping o checkpoints
